### PR TITLE
feat: implement hover state for full-expanded-route

### PR DESCRIPTION
**Pull request by samobasquiat**
# Summary

Added a hover state for full-expanded routes with showing fee & time, errors and internal-swaps for each step.

# How did you test this change?
change the variant to full-expanded and hover on swapper icons.

# Checklist:

- [x] I have performed a self-review of my code
- [x] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

### CODE REVIEW

**Comment by nikaaru** [comment]
image

The output amount is outside the hover container

**Comment by nikaaru** [comment]
image

The swapper logo should be slightly above the hover container

**Comment by nikaaru** [comment]
image

According to Figma, the background color of the tooltip should be this color

**Comment by nikaaru** [comment]
image

According to Figma, the area where the tooltip should be triggered should be less

**Comment by nikaaru** [comment]
image

The padding and box-shadow around the container during hover are wrong

**Comment by nikaaru** [comment]
image

I think that for the case where the internal swap has more than one swapper, we should show it like this

**Review by nikaaru — APPROVED** [review]

**Review by mikasackermn — APPROVED** [review]

**Pull request merged**
