### PR TITLE
fix: fix widget ui bug fixes & improvement

### PR DESCRIPTION
**Pull request by mikasackermn**
# Summary

widget ui bug fixes & improvement

Fixes # (issue)
- [x] refresh icon hover is not circular
- [x] in confirm wallet modal, footer has different style for spacing
- [x] same icon size for widget light/dark/auto icons
- [x] connected wallets tooltip

# Checklist:

- [x] I have performed a self-review of my code
- [x] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

### CODE REVIEW

**Comment by nikaaru** [comment]
image

There is no border for the Tooltip container in Figma, and it is a little far from the top

**Comment by nikaaru** [comment]
I think the name of the commit could be better
Something like this:

fix: fix widget icon size issue and add connected wallet tooltip

**Comment by mikasackermn** [comment]
> fix: fix widget icon size issue and add connected wallet tooltip

I adjusted the Tooltip based on figma, color, and shadow box; however, I would rather avoid shifting it since it could get damaged elsewhere.

**Review by nikaaru — APPROVED** [review]
Thanks, LTGM

**Pull request merged**
