### PR TITLE
fix: update design for not-selected blockchain or token

### PR DESCRIPTION
**Pull request by mikasackermn**
# Summary

Update design for not-selected blockchain or token (and color hover has been updated based on Figma.) 

Fixes # (issue)

# Checklist:

- [x] I have performed a self-review of my code
- [x] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

### CODE REVIEW

**Comment by samobasquiat** [comment]
It seems that the texts should be changed as well 
image

**Comment by samobasquiat** [comment]
when there is no output amount in Figma `Zero` color looks like inputAmount (a gray kind) .
image

**Review by samobasquiat — CHANGES_REQUESTED** [review]

**Comment by RyukTheCoder** [comment]
When no token and chain is selected and I hover on it, I think the blockchain icon should be transparent but it is white:

image

image

**Comment by RyukTheCoder** [comment]
I think when no token is selected, balance should not be visible.

image

**Review by RyukTheCoder — APPROVED** [review]
LGTM

**Pull request merged**
